title: Eighteen
timezone: America/New_York
url: 
author: Justin Jay Wang
description: > # TO DO: add description and
  Temp 18 is a typeface.
exclude:
- Gruntfile.js
- Gemfile.lock
- package.json
- README*
- node_modules
- '.gitignore'
sass:
  style: compressed
repository: justinjaywang/typeface-fall-2016
google_analytics: 
footer: >
  Eighteen, designed in the fall of two thousand and sixteen for [Type at Cooper](http://coopertype.org)'s Principles of Typeface Design.