title: Eighteen
timezone: America/New_York
url: http://eighteen.justinjay.wang
author: Justin Jay Wang
description: >
  A humanist sans.
exclude:
- Gruntfile.js
- Gemfile.lock
- package.json
- README*
- node_modules
- '.gitignore'
sass:
  style: compressed
repository: justinjaywang/typeface-fall-2016
google_analytics: 
header: >
  Eighteen: a humanist sans
footer: >
  Eighteen, designed by [Justin Jay Wang](http://justinjay.wang) for [Type at Cooper](http://coopertype.org)'s Principles of Typeface Design, fall two thousand and sixteen.